extends: standard
plugins:
  - standard
  - promise
  - import
  - json
  - flowtype

parserOptions:
  ecmaVersion: 7
  sourceType: "module"
  ecmaFeatures:
    impliedStrict: true

env:
  mocha: true
  node: true
  es6: true

parser: "babel-eslint"

rules:
  semi: 
    - 2
    - "always"
  camelcase: 
    - 2
    - properties: "always"
  comma-dangle: 
    - 2
    - "only-multiline"
  indent: 
    - 2
    - 2
  padded-blocks: 
    - 2
    - "never"
  operator-linebreak: 
    - 2
    - "after"
  space-before-function-paren: 
    - 2
    - "never"
  space-in-parens: 
    - 2
    - "never"
  no-tabs:
    0
  flowtype/generic-spacing:
    - 2
    - "never"
  flowtype/no-primitive-constructor-types:
    2
  flowtype/object-type-delimiter:
    - 2
    - "comma"
  flowtype/require-parameter-type:
    2
  flowtype/require-return-type:
    - 2
    - "always"
    - annotateUndefined: never
  flowtype/require-valid-file-annotation: 
    2
  flowtype/semi:
    - 2
    - "always"
  flowtype/space-after-type-colon:
    - 2
    - "always"
  flowtype/space-before-generic-bracket:
    - 2
    - "never"
  flowtype/space-before-type-colon:
    - 2
    - "never"
  flowtype/union-intersection-spacing: 
    - 2
    - "always"
  flowtype/use-flow-type: 
    1
  flowtype/valid-syntax: 
    1
settings:
  flowtype:
    onlyFilesWithFlowAnnotation:
      false
