steps:
  - label: eslint
    command: "./scripts/eslint.sh"
    agents:
      queue: ipp-regional-web:ci
      env: development
      market: rumah123

  - wait
  - label: unit test
    command: "./scripts/unit_test.sh"
    agents:
      queue: ipp-regional-web:ci
      env: development
      market: rumah123
  - wait
  - label: integration test
    command: "./scripts/integration_test.sh"
    agents:
      queue: ipp-regional-web:ci
      env: development
      market: rumah123

  - wait
  - label: " :package:"
    command: "./scripts/package.sh"
    env:
      ENV: stag
      REGION: ap-southeast-1
    agents:
      queue: ipp-regional-web:ci
      env: development
      market: rumah123
  - wait
  - trigger: "new-launch-API-deploy"
    label: ":rocket: Deploy to stag"
    async: true
    build:
     message: "${BUILDKITE_MESSAGE}-${BUILDKITE_BUILD_NUMBER}"
     env:
       BUILDKITE_BUILD_ECR: "${BUILDKITE_BUILD_NUMBER}"
