steps:
  - label: ":package: Build & Push"
    command: "./scripts/package.sh"
    env:
      ENV: stag
      REGION: ap-southeast-1
    agents:
      queue: ipp-group:ci
      env: development
      market: Group
  - wait
  - label: ":white_check_mark: Test Lint & flow"
    command: "./scripts/eslint.sh"
    env:
      ENV: stag
      REGION: ap-southeast-1
    agents:
      queue: ipp-group:ci
      env: development
      market: Group
  - wait
  - label: ":white_check_mark: Unit Test"
    command: "./scripts/unit_test.sh"
    env:
      ENV: stag
      REGION: ap-southeast-1
    agents:
      queue: ipp-group:ci
      env: development
      market: Group
  - wait
#  - label: integration test
#    command: "echo integration test " #"./scripts/integration_test.sh"
#    agents:
#      queue: ipp-regional-web:ci
#      env: development
#      market: rumah123
#  - wait
  - trigger: "new-launch-api-deploy"
    label: ":rocket: Deploy to stag"
    async: true
    build:
     message: "${BUILDKITE_MESSAGE}-${BUILDKITE_BUILD_NUMBER}"
     env:
       BUILDKITE_BUILD_ECR: "${BUILDKITE_BUILD_NUMBER}"
