// @flow
import _ from 'lodash';
import SolrClient from '../../libs/connections/SolrClient';
const LISTING_CORE = 'listing_v2';
const { client: listingClient } = new SolrClient(LISTING_CORE);

export default {
  searchProject: async(id: string): Object => {
    const conditionQ = `id:${id}`;
    //const queryListingById = listingClient.createQuery().q(conditionQ);
    return {
      "responseHeader": {
        "status": 0,
        "QTime": 0
      },
      "response": {
        "numFound": 1,
        "start": 0,
        "docs": [{
          "en_project_neighborhood": ["airport-access:Airport 1 KM",
            "bank-access:ATM & Bank 10+",
            "toll-access:Toll Gate 3 KM",
            "resto-access:Restaurant 10+",
            "hospital-access:Hospital 4 KM",
            "school-access:School 6 KM",
            "mall-access:Shopping Mall 12 KM",
            "gas-access:Gas Station 3+",
            "station-access:Train Station 6 KM"
          ],
          "is_booking": 0,
          "agent_name": "",
          "land_width": 0.0,
          "agent_phone": "",
          "id_project_neighborhood": ["airport-access:AIRPORT 1 KM",
            "bank-access:ATM & BANK 10+",
            "toll-access:GERBANG TOL 3 KM",
            "resto-access:RESTAURANT 10+",
            "hospital-access:RUMAH SAKIT 4 KM",
            "school-access:SEKOLAH 6 KM",
            "mall-access:SHOPPING MALL 12 KM",
            "gas-access:SPBU 3+",
            "station-access:STASIUN 6 KM"
          ],
          "project_neighborhood": ["airport-access:AIRPORT 1 KM",
            "bank-access:ATM & BANK 10+",
            "toll-access:GERBANG TOL 3 KM",
            "resto-access:RESTAURANT 10+",
            "hospital-access:RUMAH SAKIT 4 KM",
            "school-access:SEKOLAH 6 KM",
            "mall-access:SHOPPING MALL 12 KM",
            "gas-access:SPBU 3+",
            "station-access:STASIUN 6 KM"
          ],
          "view_listing": "",
          "type": "np",
          "project_name": "TESTING TOC",
          "price_min": "0",
          "is_referral": 1,
          "connectivity": 0,
          "hpa_active": "",
          "price_sort": 0.0,
          "price": "0",
          "developer_district_exact": "Sudirman",
          "developer_district": "Sudirman",
          "all_image": [""],
          "booking_price": "0",
          "id": "nps1045",
          "project_promotion": "",
          "project_brandcolor": "",
          "bathroom": 0.0,
          "property_condition": "",
          "period": "",
          "subproject_name": "",
          "project_quote": "",
          "ads_email2": "-",
          "active": "2018-01-01 00:00:00",
          "servbedroom": 0.0,
          "building_length": 0.0,
          "province_name": "Banten",
          "province_exact": "Banten",
          "garage_max": 0.0,
          "is_premium": 1,
          "district_city_exact": "Daan Mogot, Tangerang",
          "district_city": "Daan Mogot, Tangerang",
          "district_city_text": "Daan Mogot, Tangerang",
          "listing_images": "[\"developments/1045/26e9246d-3276-44a9-ac62-0a76210898c3.jpg\",\"developments/1045/6657d62e-f0d6-4cf2-8989-d70ce0f691f2.jpg\",\"developments/1045/4cfe7bcb-1908-4c75-b49b-389cae000a68.jpg\",\"developments/1045/f1dec730-0f0e-4e9d-9668-fee3eb92817b.jpg\",\"developments/1045/66e69247-a818-433e-a5cc-006d2ac23894.jpg\",\"developments/1045/22ae0ac6-1fd3-4bfc-8505-b96f3ab35c4d.jpg\",\"1045/galleri/galleri-aeropolis-1-1487648420.jpg\",\"1045/galleri/galleri-aeropolis-2-1487648425.jpg\",\"primary_property/project/1045/1495425012_59225ff0df711ads_images_1045.jpg\",\"primary_property/project/1045/1495425019_59225ff850486ads_images_1045.jpg\",\"primary_property/project/1045/1495425022_59225ff7df122ads_images_1045.jpg\",\"primary_property/project/1045/1495425025_59226001447efads_images_1045.jpg\",\"primary_property/project/1045/1495425028_592260014ff9dads_images_1045.jpg\",\"primary_property/project/1045/1495425031_59226007bb1f1ads_images_1045.jpg\",\"primary_property/project/1045/1495425031_5922600435245ads_images_1045.jpg\"]",
          "is_attachment": 0,
          "tagline": "TEST TOC TAGLINE",
          "building_size_min": 0.0,
          "price_max": "0",
          "developer_company_id": 58,
          "status": "Online",
          "is_gts": 0,
          "developer_city_id": 1,
          "hpa_expired": "",
          "attachments": "{\"brochure\":\"testing/primary_property/project/1045/1521518692_pdf_1045.pdf\"}",
          "garage_min": 0.0,
          "sponsor_name_en": "Mandiri Mortgage Simulation",
          "latitude": "0E-10",
          "product_status": 1,
          "project_category": "",
          "district_code_normed": 367401,
          "en_project_segmentation": ["INVESTOR",
            "COMMERCIAL SEEKER",
            "FIRST TIME HOME BUYER"
          ],
          "image_floorplan": "",
          "building_size_max": 1908.0,
          "developer_province": "DKI Jakarta",
          "developer_province_exact": "DKI Jakarta",
          "all_image_floorplan": ["\"primary_property/project/1045/1494318685_59117e5d72c13floorplan_4.jpg\";Apartemen Residence(Tipe A & F)",
            "\"primary_property/project/1045/1494318579_59117def61735floorplan_5.png\";Apartemen Residence(Tipe Standar)",
            "\"primary_property/project/1045/1494318915_59117f40155fefloorplan_1.jpg\";Commercial Park(WareHouse)",
            "\"primary_property/project/1045/1494318836_59117ef0da04dfloorplan_2.jpg\";Commercial Park(Hotel)",
            "\"primary_property/project/1045/1494318873_59117f15f0ef1floorplan_3.jpg\";Commercial Park(Office)"
          ],
          "currency": "IDR",
          "building_width": 0.0,
          "price_step_description": "",
          "project_access": ["Bandara  - 10 menit",
            "Stasiun Tangerang - 30 menit"
          ],
          "website": "http://123.com",
          "ads_email": "superqar123@gmail.com",
          "address": "Jl. Marsekal Suryadharma, Blok A No. 1\nTangerang, Banten. Indonesia",
          "company_id": 0,
          "developer_logo": "developer/logo/developer-logo-d-1474517886.jpg",
          "garage": 0.0,
          "electricity": 0,
          "developer_contactno2": "6289432354323",
          "developer_regdate": "2012-10-12 10:26:07.0",
          "developer_contactno1": "6289653464054",
          "project_facilities": ["Kolam Renang:[\"primary_property/project/1045/1501571724_facility_71045.jpg\"]:"],
          "id_project_facilities": ["Kolam Renang:[\"primary_property/project/1045/1501571724_facility_71045.jpg\"]:"],
          "bedroom_max": 1.0,
          "contractor_id": 0,
          "province_id": 7,
          "completion_date": "01-2018",
          "updated_date": "2018-03-20 11:06:02",
          "facility": "",
          "first": "",
          "all_listing_images": ["\"developments/1045/units/3886/d7966db9-9399-4bc4-8dad-b6d5ec7054b9.jpg\";Apartemen Residence(Tipe A & F)",
            "\"developments/1045/units/3887/a4448c41-c559-4584-b0ee-0b17f4625d65.jpg\";Apartemen Residence(Tipe Standar)",
            "\"developments/1045/units/3882/e78dd028-40d8-4671-8444-5dd775aa3e08.jpg\";Commercial Park(WareHouse)",
            "\"developments/1045/units/3883/cdc80a66-4538-45d4-9c7a-29d0a585054c.jpg\";Commercial Park(Hotel)",
            "\"developments/1045/units/3884/3b695217-92ca-4cfe-ab25-2252ec8e6530.jpg\";Commercial Park(Office)"
          ],
          "agent": 0,
          "developer_district_id": 11,
          "all_video": [""],
          "is_imb": "",
          "ads_project_id": 1045,
          "developer_name": "INTILAND Development",
          "en_project_facilities": ["Swimming Pool:[\"primary_property/project/1045/1501571724_facility_71045.jpg\"]:"],
          "land_size_max": 0.0,
          "bathroom_min": 0.0,
          "project_whatsapp": "621092301321238",
          "en_project_main": ["fa-map-marker:Strategic Location:Dekat Dengan Bandara Soekarno Hatta",
            "fa-line-chart:High Investment Value:Memiliki Fasilitas Hunian, Perkantoran, hotel, dan komersial",
            "fa-star:Premium Location:Kawasan yang terintegrasi dengan fasilitas lainnya"
          ],
          "furniture_condition": "",
          "land_length": 0.0,
          "property_ref_id": 0,
          "developer_description": ".",
          "logo": "[\"developments/1045/fa15515e-dfdd-4546-8131-3570a0038564.jpg\"]",
          "land_size_min": 0.0,
          "stock": 0,
          "bedroom_min": 0.0,
          "bathroom_max": 1.0,
          "longitude": "0E-10",
          "group": [""],
          "area": "Daan Mogot, Tangerang, Banten",
          "area_exact": "Daan Mogot, Tangerang, Banten",
          "image": "[\"1045/galleri/galleri-aeropolis-1-1487648420.jpg\"]",
          "pasar_kpr_id": "0",
          "developer_city_exact": "Jakarta Selatan",
          "developer_city": "Jakarta Selatan",
          "siteplan_description": "[\"Aeropolis\"]",
          "all_360_video": [""],
          "architect_id": 0,
          "background_image": "[\"primary_property/project/1045/1501571520_background_1045.jpg\"]",
          "ads_propertyname": "",
          "installment": "0",
          "id_key_point": ["Lokasi Strategis:Dekat Dengan Bandara Soekarno Hatta",
            "Nilai Investasi Tinggi:Memiliki Fasilitas Hunian, Perkantoran, hotel, dan komersial",
            "Kawasan Premium:Kawasan yang terintegrasi dengan fasilitas lainnya"
          ],
          "developer_user_id": 783528,
          "city_id": 6,
          "price_denom": "",
          "en_key_point": ["Strategic Location:Dekat Dengan Bandara Soekarno Hatta",
            "High Investment Value:Memiliki Fasilitas Hunian, Perkantoran, hotel, dan komersial",
            "Premium Location:Kawasan yang terintegrasi dengan fasilitas lainnya"
          ],
          "developer_website": "",
          "developer_province_id": 1,
          "certificate": "",
          "description": "DESCRIPTION TOC",
          "url_sponsor": "https://www.rumah123.com/kpr-mandiri",
          "architect_name": "",
          "video": "",
          "price_step": "0",
          "project_segmentation": ["INVESTOR",
            "COMMERCIAL SEEKER",
            "FIRST TIME HOME BUYER"
          ],
          "id_project_segmentation": ["INVESTOR",
            "COMMERCIAL SEEKER",
            "FIRST TIME HOME BUYER"
          ],
          "ads_contact": "6287808784500",
          "qty_unit": 5,
          "hpa_status": "",
          "contractor_name": "",
          "district_name": "Daan Mogot",
          "district_exact": "Daan Mogot",
          "city_name": "Tangerang",
          "city_exact": "Tangerang",
          "expired": "2018-04-04 00:00:00",
          "attachment": "",
          "sponsor_name_id": "Simulasi KPR Mandiri",
          "subtype": ["ap",
            "wa",
            "cs",
            "of"
          ],
          "is_sold": "",
          "developer_email": "ecangkem@gmail.com",
          "phoneline": 0,
          "company": "",
          "floor": 0.0,
          "views": 20205,
          "project_main": ["fa-map-marker:Lokasi Strategis:Dekat Dengan Bandara Soekarno Hatta",
            "fa-line-chart:Nilai Investasi Tinggi:Memiliki Fasilitas Hunian, Perkantoran, hotel, dan komersial",
            "fa-star:Kawasan Premium:Kawasan yang terintegrasi dengan fasilitas lainnya"
          ],
          "id_project_main": ["fa-map-marker:Lokasi Strategis:Dekat Dengan Bandara Soekarno Hatta",
            "fa-line-chart:Nilai Investasi Tinggi:Memiliki Fasilitas Hunian, Perkantoran, hotel, dan komersial",
            "fa-star:Kawasan Premium:Kawasan yang terintegrasi dengan fasilitas lainnya"
          ],
          "developer_brandcolor": "#2d17c1",
          "land_size": 0.0,
          "image_siteplan": "[\"primary_property/project/1045/1495425112_siteplan_1045.jpg\"]",
          "architect_logo": "",
          "city_province": "Tangerang, Banten",
          "city_province_text": "Tangerang, Banten",
          "city_province_exact": "Tangerang, Banten",
          "bedroom": 0.0,
          "360_video": "",
          "contractor_logo": "",
          "enable_gmaps": "0",
          "ads_contact2": "-",
          "infloor": 0.0,
          "building_size": 0.0,
          "featured_event": 0,
          "district_id": 8245,
          "created_date": "2015-12-14 00:00:00.0",
          "category": "s",
          "servbathroom": 0.0,
          "latlng": "0.0000000000,0.0000000000",
          "developer_address": "Jln. 94dd2e7d2f no.713",
          "_version_": 1595713287760117760
        }]
      }
    };
    //return listingClient.searchAsync(queryListingById);
  },
  searchChildListing: async(id: string): Object => {
    const conditionQ = id ? `parent_id:${id}` : '*:*';
    /*const queryListingById = listingClient
      .createQuery()
      .q(conditionQ)
      .start(0)
      .rows(100);
    return listingClient.searchAsync(queryListingById);
  */
    return {
      "responseHeader":{
        "status":0,
        "QTime":1},
      "response":{"numFound":5,"start":0,"docs":[
          {
            "is_booking":0,
            "agent_name":"",
            "land_width":0.0,
            "agent_phone":"",
            "project_neighborhood":[""],
            "view_listing":"",
            "type":"np",
            "project_name":"",
            "connectivity":0,
            "hpa_active":"",
            "price_sort":0.0,
            "price":"0.000",
            "booking_price":"0.000",
            "id":"aps4",
            "project_promotion":"",
            "bathroom":1.0,
            "property_condition":"",
            "period":"",
            "subproject_name":"Apartemen Residence",
            "project_quote":"",
            "ads_email2":"",
            "active":"2018-01-01 00:00:00",
            "servbedroom":0.0,
            "building_length":0.0,
            "province_name":"Banten",
            "province_exact":"Banten",
            "is_premium":1,
            "district_city":"Daan Mogot, Tangerang",
            "district_city_text":"Daan Mogot, Tangerang",
            "district_city_exact":"Daan Mogot, Tangerang",
            "listing_images":"[\"developments/1045/units/3886/d7966db9-9399-4bc4-8dad-b6d5ec7054b9.jpg\"]",
            "is_attachment":0,
            "tagline":"Tipe A & F",
            "developer_company_id":0,
            "status":"Online",
            "is_gts":0,
            "hpa_expired":"",
            "sponsor_name_en":"Mandiri Mortgage Simulation",
            "latitude":"",
            "product_status":1,
            "project_category":"tower",
            "district_code_normed":367401,
            "image_floorplan":"[\"primary_property/project/1045/1494318685_59117e5d72c13floorplan_4.jpg\"]",
            "currency":"IDR",
            "building_width":0.0,
            "price_step_description":"[]",
            "unit_image":[""],
            "project_access":[""],
            "website":"",
            "ads_email":"",
            "address":"",
            "company_id":0,
            "developer_logo":"",
            "garage":0.0,
            "electricity":0,
            "developer_contactno2":"",
            "developer_regdate":"",
            "developer_contactno1":"",
            "unit_360_video":[""],
            "project_facilities":[""],
            "unit_video":[""],
            "contractor_id":0,
            "province_id":7,
            "updated_date":"2018-03-20 11:06:02",
            "facility":"",
            "first":"2017-04-18 16:09:23",
            "agent":0,
            "is_imb":"0",
            "ads_project_id":1045,
            "developer_name":"",
            "furniture_condition":"",
            "land_length":0.0,
            "property_ref_id":0,
            "developer_description":"",
            "logo":"",
            "stock":0,
            "longitude":"",
            "group":[""],
            "area_exact":"Daan Mogot, Tangerang, Banten",
            "area":"Daan Mogot, Tangerang, Banten",
            "image":"",
            "pasar_kpr_id":"0",
            "siteplan_description":"",
            "architect_id":0,
            "background_image":"",
            "ads_propertyname":"",
            "parent_id":"nps1045",
            "unit_image_floorplan":["\"primary_property/project/1045/1494318685_59117e5d72c13floorplan_4.jpg\""],
            "installment":"0.0",
            "city_id":6,
            "price_denom":"0",
            "developer_website":"",
            "unit_listing_images":["\"developments/1045/units/3886/d7966db9-9399-4bc4-8dad-b6d5ec7054b9.jpg\""],
            "certificate":"",
            "description":"[\"...\"]",
            "url_sponsor":"https://www.rumah123.com/kpr-mandiri",
            "architect_name":"",
            "video":"",
            "price_step":"0.000",
            "project_segmentation":[""],
            "ads_contact":"",
            "qty_unit":0,
            "hpa_status":"",
            "contractor_name":"",
            "district_name":"Daan Mogot",
            "district_exact":"Daan Mogot",
            "city_exact":"Tangerang",
            "city_name":"Tangerang",
            "expired":"2018-04-04 00:00:00",
            "attachment":"",
            "sponsor_name_id":"Simulasi KPR Mandiri",
            "subtype":["ap"],
            "is_sold":"n",
            "developer_email":"",
            "phoneline":0,
            "company":"",
            "floor":0.0,
            "views":0,
            "project_main":[""],
            "land_size":0.0,
            "image_siteplan":"",
            "architect_logo":"",
            "city_province":"Tangerang, Banten",
            "city_province_text":"Tangerang, Banten",
            "city_province_exact":"Tangerang, Banten",
            "bedroom":1.0,
            "360_video":"",
            "contractor_logo":"",
            "enable_gmaps":"0",
            "ads_contact2":"",
            "infloor":0.0,
            "building_size":1609.0,
            "featured_event":0,
            "district_id":8245,
            "created_date":"2017-04-18 16:09:23.0",
            "category":"s",
            "servbathroom":0.0,
            "latlng":",",
            "developer_address":"",
            "_version_":1595713287840858112},
          {
            "is_booking":0,
            "agent_name":"",
            "land_width":0.0,
            "agent_phone":"",
            "project_neighborhood":[""],
            "view_listing":"",
            "type":"np",
            "project_name":"",
            "connectivity":0,
            "hpa_active":"",
            "price_sort":0.0,
            "price":"0.000",
            "booking_price":"0.000",
            "id":"aps5",
            "project_promotion":"",
            "bathroom":1.0,
            "property_condition":"",
            "period":"",
            "subproject_name":"Apartemen Residence",
            "project_quote":"",
            "ads_email2":"",
            "active":"2018-01-01 00:00:00",
            "servbedroom":0.0,
            "building_length":0.0,
            "province_name":"Banten",
            "province_exact":"Banten",
            "is_premium":1,
            "district_city":"Daan Mogot, Tangerang",
            "district_city_text":"Daan Mogot, Tangerang",
            "district_city_exact":"Daan Mogot, Tangerang",
            "listing_images":"[\"developments/1045/units/3887/a4448c41-c559-4584-b0ee-0b17f4625d65.jpg\"]",
            "is_attachment":0,
            "tagline":"Tipe Standar",
            "developer_company_id":0,
            "status":"Online",
            "is_gts":0,
            "hpa_expired":"",
            "sponsor_name_en":"Mandiri Mortgage Simulation",
            "latitude":"",
            "product_status":1,
            "project_category":"tower",
            "district_code_normed":367401,
            "image_floorplan":"[\"primary_property/project/1045/1494318579_59117def61735floorplan_5.png\"]",
            "currency":"IDR",
            "building_width":0.0,
            "price_step_description":"[]",
            "unit_image":[""],
            "project_access":[""],
            "website":"",
            "ads_email":"",
            "address":"",
            "company_id":0,
            "developer_logo":"",
            "garage":0.0,
            "electricity":0,
            "developer_contactno2":"",
            "developer_regdate":"",
            "developer_contactno1":"",
            "unit_360_video":[""],
            "project_facilities":[""],
            "unit_video":[""],
            "contractor_id":0,
            "province_id":7,
            "updated_date":"2018-03-20 11:06:02",
            "facility":"",
            "first":"2017-04-18 16:09:23",
            "agent":0,
            "is_imb":"0",
            "ads_project_id":1045,
            "developer_name":"",
            "furniture_condition":"",
            "land_length":0.0,
            "property_ref_id":0,
            "developer_description":"",
            "logo":"",
            "stock":0,
            "longitude":"",
            "group":[""],
            "area_exact":"Daan Mogot, Tangerang, Banten",
            "area":"Daan Mogot, Tangerang, Banten",
            "image":"",
            "pasar_kpr_id":"0",
            "siteplan_description":"",
            "architect_id":0,
            "background_image":"",
            "ads_propertyname":"",
            "parent_id":"nps1045",
            "unit_image_floorplan":["\"primary_property/project/1045/1494318579_59117def61735floorplan_5.png\""],
            "installment":"0.0",
            "city_id":6,
            "price_denom":"0",
            "developer_website":"",
            "unit_listing_images":["\"developments/1045/units/3887/a4448c41-c559-4584-b0ee-0b17f4625d65.jpg\""],
            "certificate":"",
            "description":"[\"...\"]",
            "url_sponsor":"https://www.rumah123.com/kpr-mandiri",
            "architect_name":"",
            "video":"",
            "price_step":"0.000",
            "project_segmentation":[""],
            "ads_contact":"",
            "qty_unit":0,
            "hpa_status":"",
            "contractor_name":"",
            "district_name":"Daan Mogot",
            "district_exact":"Daan Mogot",
            "city_exact":"Tangerang",
            "city_name":"Tangerang",
            "expired":"2018-04-04 00:00:00",
            "attachment":"",
            "sponsor_name_id":"Simulasi KPR Mandiri",
            "subtype":["ap"],
            "is_sold":"n",
            "developer_email":"",
            "phoneline":0,
            "company":"",
            "floor":0.0,
            "views":0,
            "project_main":[""],
            "land_size":0.0,
            "image_siteplan":"",
            "architect_logo":"",
            "city_province":"Tangerang, Banten",
            "city_province_text":"Tangerang, Banten",
            "city_province_exact":"Tangerang, Banten",
            "bedroom":1.0,
            "360_video":"",
            "contractor_logo":"",
            "enable_gmaps":"0",
            "ads_contact2":"",
            "infloor":0.0,
            "building_size":1908.0,
            "featured_event":0,
            "district_id":8245,
            "created_date":"2017-04-18 16:09:23.0",
            "category":"s",
            "servbathroom":0.0,
            "latlng":",",
            "developer_address":"",
            "_version_":1595713287840858113},
          {
            "is_booking":0,
            "agent_name":"",
            "land_width":0.0,
            "agent_phone":"",
            "project_neighborhood":[""],
            "view_listing":"",
            "type":"np",
            "project_name":"",
            "connectivity":0,
            "hpa_active":"",
            "price_sort":0.0,
            "price":"0.000",
            "booking_price":"0.000",
            "id":"css2",
            "project_promotion":"",
            "bathroom":0.0,
            "property_condition":"",
            "period":"",
            "subproject_name":"Commercial Park",
            "project_quote":"",
            "ads_email2":"",
            "active":"2018-01-01 00:00:00",
            "servbedroom":0.0,
            "building_length":0.0,
            "province_name":"Banten",
            "province_exact":"Banten",
            "is_premium":1,
            "district_city":"Daan Mogot, Tangerang",
            "district_city_text":"Daan Mogot, Tangerang",
            "district_city_exact":"Daan Mogot, Tangerang",
            "listing_images":"[\"developments/1045/units/3883/cdc80a66-4538-45d4-9c7a-29d0a585054c.jpg\"]",
            "is_attachment":0,
            "tagline":"Hotel",
            "developer_company_id":0,
            "status":"Online",
            "is_gts":0,
            "hpa_expired":"",
            "sponsor_name_en":"Mandiri Mortgage Simulation",
            "latitude":"",
            "product_status":1,
            "project_category":"blok",
            "district_code_normed":367401,
            "image_floorplan":"[\"primary_property/project/1045/1494318836_59117ef0da04dfloorplan_2.jpg\"]",
            "currency":"IDR",
            "building_width":0.0,
            "price_step_description":"[]",
            "unit_image":[""],
            "project_access":[""],
            "website":"",
            "ads_email":"",
            "address":"",
            "company_id":0,
            "developer_logo":"",
            "garage":0.0,
            "electricity":0,
            "developer_contactno2":"",
            "developer_regdate":"",
            "developer_contactno1":"",
            "unit_360_video":[""],
            "project_facilities":[""],
            "unit_video":[""],
            "contractor_id":0,
            "province_id":7,
            "updated_date":"2018-03-20 11:06:02",
            "facility":"",
            "first":"2017-04-18 16:09:23",
            "agent":0,
            "is_imb":"0",
            "ads_project_id":1045,
            "developer_name":"",
            "furniture_condition":"",
            "land_length":0.0,
            "property_ref_id":0,
            "developer_description":"",
            "logo":"",
            "stock":0,
            "longitude":"",
            "group":[""],
            "area_exact":"Daan Mogot, Tangerang, Banten",
            "area":"Daan Mogot, Tangerang, Banten",
            "image":"",
            "pasar_kpr_id":"0",
            "siteplan_description":"",
            "architect_id":0,
            "background_image":"",
            "ads_propertyname":"",
            "parent_id":"nps1045",
            "unit_image_floorplan":["\"primary_property/project/1045/1494318836_59117ef0da04dfloorplan_2.jpg\""],
            "installment":"0.0",
            "city_id":6,
            "price_denom":"0",
            "developer_website":"",
            "unit_listing_images":["\"developments/1045/units/3883/cdc80a66-4538-45d4-9c7a-29d0a585054c.jpg\""],
            "certificate":"",
            "description":"[\"...\"]",
            "url_sponsor":"https://www.rumah123.com/kpr-mandiri",
            "architect_name":"",
            "video":"",
            "price_step":"0.000",
            "project_segmentation":[""],
            "ads_contact":"",
            "qty_unit":0,
            "hpa_status":"",
            "contractor_name":"",
            "district_name":"Daan Mogot",
            "district_exact":"Daan Mogot",
            "city_exact":"Tangerang",
            "city_name":"Tangerang",
            "expired":"2018-04-04 00:00:00",
            "attachment":"",
            "sponsor_name_id":"Simulasi KPR Mandiri",
            "subtype":["cs"],
            "is_sold":"n",
            "developer_email":"",
            "phoneline":0,
            "company":"",
            "floor":0.0,
            "views":0,
            "project_main":[""],
            "land_size":0.0,
            "image_siteplan":"",
            "architect_logo":"",
            "city_province":"Tangerang, Banten",
            "city_province_text":"Tangerang, Banten",
            "city_province_exact":"Tangerang, Banten",
            "bedroom":0.0,
            "360_video":"",
            "contractor_logo":"",
            "enable_gmaps":"0",
            "ads_contact2":"",
            "infloor":0.0,
            "building_size":0.0,
            "featured_event":0,
            "district_id":8245,
            "created_date":"2017-04-18 16:09:23.0",
            "category":"s",
            "servbathroom":0.0,
            "latlng":",",
            "developer_address":"",
            "_version_":1595713287842955265},
          {
            "is_booking":0,
            "agent_name":"",
            "land_width":0.0,
            "agent_phone":"",
            "project_neighborhood":[""],
            "view_listing":"",
            "type":"np",
            "project_name":"",
            "connectivity":0,
            "hpa_active":"",
            "price_sort":0.0,
            "price":"0.000",
            "booking_price":"0.000",
            "id":"ofs3",
            "project_promotion":"",
            "bathroom":0.0,
            "property_condition":"",
            "period":"",
            "subproject_name":"Commercial Park",
            "project_quote":"",
            "ads_email2":"",
            "active":"2018-01-01 00:00:00",
            "servbedroom":0.0,
            "building_length":0.0,
            "province_name":"Banten",
            "province_exact":"Banten",
            "is_premium":1,
            "district_city":"Daan Mogot, Tangerang",
            "district_city_text":"Daan Mogot, Tangerang",
            "district_city_exact":"Daan Mogot, Tangerang",
            "listing_images":"[\"developments/1045/units/3884/3b695217-92ca-4cfe-ab25-2252ec8e6530.jpg\"]",
            "is_attachment":0,
            "tagline":"Office",
            "developer_company_id":0,
            "status":"Online",
            "is_gts":0,
            "hpa_expired":"",
            "sponsor_name_en":"Mandiri Mortgage Simulation",
            "latitude":"",
            "product_status":1,
            "project_category":"blok",
            "district_code_normed":367401,
            "image_floorplan":"[\"primary_property/project/1045/1494318873_59117f15f0ef1floorplan_3.jpg\"]",
            "currency":"IDR",
            "building_width":0.0,
            "price_step_description":"[]",
            "unit_image":[""],
            "project_access":[""],
            "website":"",
            "ads_email":"",
            "address":"",
            "company_id":0,
            "developer_logo":"",
            "garage":0.0,
            "electricity":0,
            "developer_contactno2":"",
            "developer_regdate":"",
            "developer_contactno1":"",
            "unit_360_video":[""],
            "project_facilities":[""],
            "unit_video":[""],
            "contractor_id":0,
            "province_id":7,
            "updated_date":"2018-03-20 11:06:02",
            "facility":"",
            "first":"2017-04-18 16:09:23",
            "agent":0,
            "is_imb":"0",
            "ads_project_id":1045,
            "developer_name":"",
            "furniture_condition":"",
            "land_length":0.0,
            "property_ref_id":0,
            "developer_description":"",
            "logo":"",
            "stock":0,
            "longitude":"",
            "group":[""],
            "area_exact":"Daan Mogot, Tangerang, Banten",
            "area":"Daan Mogot, Tangerang, Banten",
            "image":"",
            "pasar_kpr_id":"0",
            "siteplan_description":"",
            "architect_id":0,
            "background_image":"",
            "ads_propertyname":"",
            "parent_id":"nps1045",
            "unit_image_floorplan":["\"primary_property/project/1045/1494318873_59117f15f0ef1floorplan_3.jpg\""],
            "installment":"0.0",
            "city_id":6,
            "price_denom":"0",
            "developer_website":"",
            "unit_listing_images":["\"developments/1045/units/3884/3b695217-92ca-4cfe-ab25-2252ec8e6530.jpg\""],
            "certificate":"",
            "description":"[\"...\"]",
            "url_sponsor":"https://www.rumah123.com/kpr-mandiri",
            "architect_name":"",
            "video":"",
            "price_step":"0.000",
            "project_segmentation":[""],
            "ads_contact":"",
            "qty_unit":0,
            "hpa_status":"",
            "contractor_name":"",
            "district_name":"Daan Mogot",
            "district_exact":"Daan Mogot",
            "city_exact":"Tangerang",
            "city_name":"Tangerang",
            "expired":"2018-04-04 00:00:00",
            "attachment":"",
            "sponsor_name_id":"Simulasi KPR Mandiri",
            "subtype":["of"],
            "is_sold":"n",
            "developer_email":"",
            "phoneline":0,
            "company":"",
            "floor":0.0,
            "views":0,
            "project_main":[""],
            "land_size":0.0,
            "image_siteplan":"",
            "architect_logo":"",
            "city_province":"Tangerang, Banten",
            "city_province_text":"Tangerang, Banten",
            "city_province_exact":"Tangerang, Banten",
            "bedroom":0.0,
            "360_video":"",
            "contractor_logo":"",
            "enable_gmaps":"0",
            "ads_contact2":"",
            "infloor":0.0,
            "building_size":0.0,
            "featured_event":0,
            "district_id":8245,
            "created_date":"2017-04-18 16:09:23.0",
            "category":"s",
            "servbathroom":0.0,
            "latlng":",",
            "developer_address":"",
            "_version_":1595713287867072513},
          {
            "is_booking":0,
            "agent_name":"",
            "land_width":0.0,
            "agent_phone":"",
            "project_neighborhood":[""],
            "view_listing":"",
            "type":"np",
            "project_name":"",
            "connectivity":0,
            "hpa_active":"",
            "price_sort":0.0,
            "price":"0.000",
            "booking_price":"0.000",
            "id":"was1",
            "project_promotion":"",
            "bathroom":0.0,
            "property_condition":"",
            "period":"",
            "subproject_name":"Commercial Park",
            "project_quote":"",
            "ads_email2":"",
            "active":"2018-01-01 00:00:00",
            "servbedroom":0.0,
            "building_length":0.0,
            "province_name":"Banten",
            "province_exact":"Banten",
            "is_premium":1,
            "district_city":"Daan Mogot, Tangerang",
            "district_city_text":"Daan Mogot, Tangerang",
            "district_city_exact":"Daan Mogot, Tangerang",
            "listing_images":"[\"developments/1045/units/3882/e78dd028-40d8-4671-8444-5dd775aa3e08.jpg\"]",
            "is_attachment":0,
            "tagline":"WareHouse",
            "developer_company_id":0,
            "status":"Online",
            "is_gts":0,
            "hpa_expired":"",
            "sponsor_name_en":"Mandiri Mortgage Simulation",
            "latitude":"",
            "product_status":1,
            "project_category":"blok",
            "district_code_normed":367401,
            "image_floorplan":"[\"primary_property/project/1045/1494318915_59117f40155fefloorplan_1.jpg\"]",
            "currency":"IDR",
            "building_width":0.0,
            "price_step_description":"[]",
            "unit_image":[""],
            "project_access":[""],
            "website":"",
            "ads_email":"",
            "address":"",
            "company_id":0,
            "developer_logo":"",
            "garage":0.0,
            "electricity":0,
            "developer_contactno2":"",
            "developer_regdate":"",
            "developer_contactno1":"",
            "unit_360_video":[""],
            "project_facilities":[""],
            "unit_video":[""],
            "contractor_id":0,
            "province_id":7,
            "updated_date":"2018-03-20 11:06:02",
            "facility":"",
            "first":"2017-04-18 16:09:23",
            "agent":0,
            "is_imb":"0",
            "ads_project_id":1045,
            "developer_name":"",
            "furniture_condition":"",
            "land_length":0.0,
            "property_ref_id":0,
            "developer_description":"",
            "logo":"",
            "stock":0,
            "longitude":"",
            "group":[""],
            "area_exact":"Daan Mogot, Tangerang, Banten",
            "area":"Daan Mogot, Tangerang, Banten",
            "image":"",
            "pasar_kpr_id":"0",
            "siteplan_description":"",
            "architect_id":0,
            "background_image":"",
            "ads_propertyname":"",
            "parent_id":"nps1045",
            "unit_image_floorplan":["\"primary_property/project/1045/1494318915_59117f40155fefloorplan_1.jpg\""],
            "installment":"0.0",
            "city_id":6,
            "price_denom":"0",
            "developer_website":"",
            "unit_listing_images":["\"developments/1045/units/3882/e78dd028-40d8-4671-8444-5dd775aa3e08.jpg\""],
            "certificate":"",
            "description":"[\"...\"]",
            "url_sponsor":"https://www.rumah123.com/kpr-mandiri",
            "architect_name":"",
            "video":"",
            "price_step":"0.000",
            "project_segmentation":[""],
            "ads_contact":"",
            "qty_unit":0,
            "hpa_status":"",
            "contractor_name":"",
            "district_name":"Daan Mogot",
            "district_exact":"Daan Mogot",
            "city_exact":"Tangerang",
            "city_name":"Tangerang",
            "expired":"2018-04-04 00:00:00",
            "attachment":"",
            "sponsor_name_id":"Simulasi KPR Mandiri",
            "subtype":["wa"],
            "is_sold":"n",
            "developer_email":"",
            "phoneline":0,
            "company":"",
            "floor":0.0,
            "views":0,
            "project_main":[""],
            "land_size":0.0,
            "image_siteplan":"",
            "architect_logo":"",
            "city_province":"Tangerang, Banten",
            "city_province_text":"Tangerang, Banten",
            "city_province_exact":"Tangerang, Banten",
            "bedroom":0.0,
            "360_video":"",
            "contractor_logo":"",
            "enable_gmaps":"0",
            "ads_contact2":"",
            "infloor":0.0,
            "building_size":0.0,
            "featured_event":0,
            "district_id":8245,
            "created_date":"2017-04-18 16:09:23.0",
            "category":"s",
            "servbathroom":0.0,
            "latlng":",",
            "developer_address":"",
            "_version_":1595713287868121088}]
      }};    
  },
  searchProjectByOrganisation: async(
    id: string,
    excludeProjectId: string,
    paging: Object
  ): Object => {
    let conditionQ = `developer_company_id:${id}`;
    if (!_.isEmpty(excludeProjectId)) {
      conditionQ += ` AND -id:${excludeProjectId}`;
    }

    const pageStart = (paging.pageToken - 1) * paging.pageSize;
    const queryListingById = listingClient
      .createQuery()
      .q(conditionQ)
      .start(pageStart)
      .rows(paging.pageSize);
    return listingClient.searchAsync(queryListingById);
  },
  searchProjectAccessByProjectId: async(id: string): Object => {
    const conditionQ = `id:${id}`;
    const queryProjectAccess = listingClient
      .createQuery()
      .q(conditionQ)
      .matchFilter('en_project_access', '[* TO *]');
    return listingClient.searchAsync(queryProjectAccess);
  },
  searchProjectByUserId: async(userId: string, start: number, row: number): Object => {
    const conditionQ = `developer_user_id:${userId}`;
    const queryListingByUserId =
    listingClient
      .createQuery()
      .q(conditionQ)
      .start(start)
      .rows(row); ;
    return listingClient.searchAsync(queryListingByUserId);
  }
};
